import Button from '../common/Button';
import { donationTypes } from '../../data/mockDonations';

export default function DonationForm({ form, onChange, onSubmit }) {
  const update = (key, value) => onChange({ ...form, [key]: value });
  return <form onSubmit={onSubmit} className="space-y-6">
    <div><p className="eyebrow">Food details</p><div className="mt-3 grid gap-4 md:grid-cols-2"><label className="md:col-span-2 text-sm font-medium">Food name<input className="field mt-1.5" value={form.foodName} onChange={(e) => update('foodName', e.target.value)} placeholder="e.g. Vegetable Biryani" required /></label><label className="text-sm font-medium">Food type<select className="field mt-1.5" value={form.foodType} onChange={(e) => update('foodType', e.target.value)}>{donationTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-sm font-medium">Quantity<input type="number" min="1" className="field mt-1.5" value={form.quantity} onChange={(e) => update('quantity', e.target.value)} required /></label><label className="text-sm font-medium">Unit<select className="field mt-1.5" value={form.unit} onChange={(e) => update('unit', e.target.value)}><option>kg</option><option>portions</option><option>packets</option></select></label><label className="text-sm font-medium">Dietary type<select className="field mt-1.5" value={form.dietaryType} onChange={(e) => update('dietaryType', e.target.value)}><option>Vegetarian</option><option>Non-vegetarian</option><option>Mixed</option></select></label><label className="text-sm font-medium">Prepared / ready time<input type="datetime-local" className="field mt-1.5" value={form.readyAt} onChange={(e) => update('readyAt', e.target.value)} required /></label><label className="text-sm font-medium">Safe until<input type="datetime-local" className="field mt-1.5" value={form.safeUntil} onChange={(e) => update('safeUntil', e.target.value)} required /></label><label className="text-sm font-medium">Storage condition<select className="field mt-1.5" value={form.storageState} onChange={(e) => update('storageState', e.target.value)}><option>Hot-held</option><option>Refrigerated</option><option>Ambient</option></select></label></div></div>
    <div><p className="eyebrow">Pickup location</p><div className="mt-3 grid gap-4 md:grid-cols-2"><label className="md:col-span-2 text-sm font-medium">Address<input className="field mt-1.5" value={form.location} onChange={(e) => update('location', e.target.value)} placeholder="Restaurant address" required /></label></div></div>
    <div><p className="eyebrow">Notes</p><textarea className="field mt-3 min-h-24" value={form.notes} onChange={(e) => update('notes', e.target.value)} placeholder="Any handling or pickup notes" /></div>
    <div className="flex justify-end gap-3"><Button variant="secondary">Cancel</Button><Button type="submit">Post Donation</Button></div>
  </form>;
}
